/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./App.vue')['default']
    CommonHeader: typeof import('./components/CommonHeader/index.vue')['default']
    Index: typeof import('./views/Index.vue')['default']
    Logo: typeof import('./views/Logo/index.vue')['default']
    Mytest: typeof import('./views/Mytest.vue')['default']
    NotFound: typeof import('./views/NotFound.vue')['default']
    PageChangeComp: typeof import('./components/PageChangeComp/index.vue')['default']
    Result: typeof import('./views/Logo/result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./views/Logo/select.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanEmpty: typeof import('vant/es')['Empty']
  }
}
